---

- name: install supervisord
  yum:
    name: supervisor
    state: present

- name: application.conf
  template:
    src: application.conf.j2
    dest: /etc/supervisor/conf.d/application.conf
    owner: root
    group: root
    mode: 0644

- name: nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/supervisor/conf.d/nginx.conf
    owner: root
    group: root
    mode: 0644
