---

- name: check pip
  stat:
    path: /usr/local/bin/pip
  register: check_pip

- name: pip install
  command: easy_install pip
  when: check_pip.stat.exists == False

- name: pip upgrade
  command: easy_install --upgrade pip
  when: check_pip.stat.exists == False

- name: check supervisord
  stat:
    path: /usr/local/bin/supervisord
  register: check_supervisord

- name: install supervisord
  command: /usr/local/bin/pip install supervisor
  when: check_supervisord.stat.exists == False

- name: create supervisord conf directory
  file:
    path: /etc/supervisord/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create supervisord log directory
  file:
    path: /var/log/supervisord
    state: directory
    owner: root
    group: root
    mode: 0755

- name: generate supervisord.ini
  template:
    src: supervisord.ini.j2
    dest: /etc/supervisord.ini
    owner: root
    group: root
    mode: 0644

- name: generate supervisord init script
  template:
    src: supervisord.j2
    dest: /etc/init.d/supervisord
    owner: root
    group: root
    mode: 0700

- name: generate application.ini
  template:
    src: application.ini.j2
    dest: /etc/supervisord/conf.d/application.ini
    owner: root
    group: root
    mode: 0644

- name: generate nginx.ini
  template:
    src: nginx.ini.j2
    dest: /etc/supervisord/conf.d/nginx.ini
    owner: root
    group: root
    mode: 0644

- name: service supervisord
  service:
    name: supervisord
    state: started
    enabled: yes
